"""add unique constraint for title and author

Revision ID: 4c8b4aeec392
Revises: 41a26f9c2fc7
Create Date: 2026-04-30 18:12:21.961095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c8b4aeec392'
down_revision: Union[str, Sequence[str], None] = '41a26f9c2fc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_title_author', 'books', ['title', 'author'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_title_author', 'books', type_='unique')
    # ### end Alembic commands ###
